"""Create user and prd tables

Revision ID: 6f9ca3e22e95
Revises: 
Create Date: 2025-04-15 14:28:52.829016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9ca3e22e95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('prd',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('input_prompt', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('format', sa.Enum('MARKDOWN', 'JSON', name='format'), nullable=False),
    sa.Column('template_type', sa.Enum('CRUD', 'AI_AGENT', 'SAAS', 'CUSTOM', name='templatetype'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prd_id'), 'prd', ['id'], unique=False)
    op.create_index(op.f('ix_prd_title'), 'prd', ['title'], unique=False)
    op.create_index(op.f('ix_prd_user_id'), 'prd', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prd_user_id'), table_name='prd')
    op.drop_index(op.f('ix_prd_title'), table_name='prd')
    op.drop_index(op.f('ix_prd_id'), table_name='prd')
    op.drop_table('prd')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
